stages:
  - test

tests:
  image: "python:3.7"
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - behave features/mtu_tests.feature
    - behave features/static_tests.feature
    - behave features/infos_tests.feature
  tags:
    - docker
