stages:
  - test_pip_install_requirements
#  - test_netests_main_function
  - test_functions_protocols
#  - create_merge_request_to_master

test_pip37_install_requirements:
  image: "python:3.7"
  stage: test_pip_install_requirements
  script:
    - pip version
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip freeze
  tags:
    - docker

test_pip36_install_requirements:
  image: "python:3.6"
  stage: test_pip_install_requirements
  script:
    - pip version
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip freeze
  tags:
    - docker

#test_netests_main_function:
#  stage: test_netests_main_function
#  script:
#    - netests.py -v
#    - netests.py --ansible True --test True 
#    - netests.py --ansible True --virtual True --test True
#    - netests.py --netbox True --test True 
#    - netests.py --netbox True --virtual True --test True
#    - netests.py --virtual True --test True
#    - netests.py --test True
#    - netests.py --reports True --test True
#    - netests.py --check-connectivity True --test True   

test_functions_protocols:
  stage: test_functions_protocols
  script:
    - ./features/run_tests.sh

#create_merge_request_to_master:
#  stage: create_merge_request_to_master


