image: python:3.7

stages:
  - test
  - lint

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run behave tests/features/

Python Code Lint:
  stage: lint
  script:
    - poetry run pylama .
