site_name: Netests.io
theme:
  name: material
  language: en
  palette:
    primary: purple
    accent: purple
  font:
    text: Ubuntu
    code: Ubuntu Mono

markdown_extensions:
  - pymdownx.emoji

nav:
  - index.md
  - installation.md