site_name: Netests.io
theme:
  name: material
  language: en
  palette:
    primary: purple
    accent: purple
  font:
    text: Ubuntu
    code: Ubuntu Mono

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

nav:
  - index.md
  - vendors_and_protocols.md
  - protocols.md
  - protocols_arguments.md
  - installation.md
  - configuration.md
  - run.md
  - arguments.md
  - inventory.md
  - source_of_truth.md
  - data_models.md
  - netests_cli.md
  - troubleshooting.md
  - device_used.md
  - roadmap.md
  - license.md
  - contributors.md
  - divers.md
  