# ################################################
#
# ROUTER
#


# ################################################
#
# SPINE
#
spine01:
  hostname: 10.0.5.101
  username: cumulus
  password: CumulusLinux!
  port: 22
  platform: linux
  groups:
    - global
    - spine
  data:
    vrfs:
      - name: mgmt
        bgp: True
# ################################################
#
# EXIT
#

# ################################################
#
# LEAF
#