# ################################################


# ################################################
#
# ROUTER
#


# ################################################
#
# SPINE
#
spine01:
  hostname: 192.168.254.10
  username: admin
  password: juniper123
  port: 22101
  platform: junos
  groups:
    - global
    - spine
  data:
    oob_ip: 10.0.4.101

spine02:
  hostname: 192.168.254.10
  username: rwa
  password: rwa
  port: 22102
  platform: extreme_vsp
  groups:
    - global
    - spine
  data:
    oob_ip: 10.0.4.102

# ################################################
#
# EXIT
#

# ################################################
#
# LEAF
#
leaf01:
  hostname: 192.168.254.10
  username: cumuls
  password: CumulusLinux!
  port: 22201
  platform: linux
  groups:
    - global
    - leaf
  data:
    oob_ip: 10.0.4.201

leaf02:
  hostname: 192.168.254.10
  username: admin
  password: arista123
  port: 22202
  platform: cisco_nxos
  groups:
    - global
    - leaf
  data:
    oob_ip: 10.0.4.201

leaf03:
  hostname: 192.168.254.10
  username: admin
  password: cisco123
  port: 22203
  platform: cisco_ios
  groups:
    - global
    - leaf
  data:
    oob_ip: 10.0.4.203