---
core:
    num_workers: 100

inventory:
  plugin: nornir.plugins.inventory.netbox.NBInventory
  options:
    nb_url: 'http://192.168.254.7:32769'
    nb_token: 'c04bcc52e990f3fa428a2f4bfa671ba6978561f2'
    ssl_verify: False
  #transform_function: "helpers.adapt_user_password"