---
core:
    num_workers: 10

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/hosts.yml"
        group_file: "inventory/groups.yml"
        defaults_file: "inventory/defaults.yml"