---
core:
    num_workers: 10

inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "inventory/nornir/std/hosts.yml"
        group_file: "inventory/nornir/std/groups.yml"
        defaults_file: "inventory/nornir/std/defaults.yml"